# Generated by Django 3.1.7 on 2021-03-05 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_login_profile_snippet_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='code_input',
            new_name='Input',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='code_language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='code_description',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
