# Generated by Django 3.1.7 on 2021-03-06 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Input',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='Title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='snip_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snip_desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snip_input',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='snip_lang',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='core.user'),
        ),
    ]
