# Generated by Django 3.1.7 on 2021-03-06 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210305_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='Input',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='snippet',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
