# Generated by Django 3.1.7 on 2021-03-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210306_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
