# Generated by Django 3.1.7 on 2021-03-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210308_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
