# Generated by Django 3.1.7 on 2021-03-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210309_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_added',
        ),
    ]
